---
# имя любого tags не должно входить в имя любого tags, кроме себя самого

- debug: msg="Please, specify the --tags"
  when: "'all' in ansible_run_tags"
  tags: [pgpool_install,pgpool_remove]

- meta: end_play
  when: "'all' in ansible_run_tags"
  tags: [pgpool_install,pgpool_remove]

- include: install.yml
  when: install_pgpool == true
  tags: [pgpool_install]

- include: remove.yml
  tags: [pgpool_remove]
