---
# имя любого tags не должно входить в имя любого tags, кроме себя самого

- debug: msg="Please, specify the --tags"
  when: "'all' in ansible_run_tags"
  tags: [etcd3_install,etcd3_remove]

- meta: end_play
  when: "'all' in ansible_run_tags"
  tags: [etcd3_install,etcd3_remove]

- include: install.yml
  tags: [etcd3_install]

- include: remove.yml
  tags: [etcd3_remove]
